- standalone/script/runserver.sh
- welcomepage/src/main/webapp/index.jsp
- Adding a video inside welcome page.
- Standalone sample data is set to true by default
> Mutliple fixes

- standalone/dockerhub/full-description.md
Improve the ODM evaluation experience when using ODM for Developers Docker image:
-added link to video
-replaced passwords with 'odmAdmin'
-added more details about Eclipse version
> story 112502

- standalone/dockerhub/full-description.md
@lgrateau Please check and push my changes.
> update KC links + eclipse version + RD links

- standalone/dockerhub/full-description.md
@lgrateau Please push my change.
> added link to Getting started

- standalone/dockerhub/full-description.md
@lgrateau Please push my changes.
> added links to samples and tutorials

- standalone/dockerhub/full-description.md
@lgrateau Please review and push my changes.
> defect 113959

- standalone/dockerhub/full-description.md
@lgrateau Please can you push my changes?
> edits in samples and tutorials links

- standalone/dockerhub/full-description.md
following discussion with Marie-Francoise
> edits to samples and tutorials sections

- standalone/dockerhub/full-description.md
@lgrateau Laurent please push the changes. Thanks.
> Changes to tutorials and samples

- standalone/dockerhub/full-description.md
@lgrateau please push to master
> updated KC links to final URLs

- .secrets.baseline
- decisionserver/decisionserverconsole/script/updateDSCConfigurations.sh
- decisionserver/decisionserverruntime/script/updateDSRConfigurations.sh
Close [RTC Defect 119193](https://jazz004.hursley.ibm.com:9443/jazz/web/projects/Business%20Events%20And%20Rules#action=com.ibm.team.workitem.viewWorkItem&id=119193)
> Add Kerberos authentication config

- standalone/dockerhub/full-description.md
Added note on memory allocation
> Defect 120101

- standalone/dockerhub/full-description.md
@lgrateau Please merge my updates
> Rule Designer link updates

- common/config/tlsSecurity.xml
- decisioncenter/config/featureManager.xml
- decisioncenter/config/httpSession.xml
- decisionserver/config/httpSession.xml
- decisionserver/decisionrunner/config/featureManager.xml
- decisionserver/decisionserverconsole/config/featureManager.xml
- decisionserver/decisionserverruntime/config/featureManager.xml
- standalone/config/featureManager.xml
- standalone/config/httpSession.xml
- standalone/config/tlsSecurity.xml
Fix [defect 124545](https://jazz004.hursley.ibm.com:9443/jazz/web/projects/Business%20Events%20And%20Rules#action=com.ibm.team.workitem.viewWorkItem&id=124545)
> Fix security settings

- decisionserver/decisionserverruntime/script/updateDSRConfigurations.sh
- standalone/Dockerfile
* Change xu configuration in ra.xml file using xmllint
* Fix script when blank line
* Remove xmllint stdout and stderr
* Discard commented lines
* Fix typo
* Create function for lisibility and add log when property to set does not exist
> Add XU configuration (#229)

- common/script/updateDatasource.sh
For https://github.ibm.com/dba/icp4a-defects/issues/2916
> Fix sed command to escape special characters in db user and password

- common/script/configureSwidTag.sh
For https://github.ibm.com/dba/icp4a-odm/issues/556
> Remove DBAMC swidtag usage

- decisionserver/decisionserverruntime/script/updateDSRConfigurations.sh
For https://github.ibm.com/dba/icp4a-odm/issues/585
> Update or add context-param in web.xml runtime

- decisionserver/decisionserverruntime/script/updateDSRConfigurations.sh
For https://github.ibm.com/dba/icp4a-odm/issues/586
> Add environment variable to enable tls auth in dsr webxml

- standalone/dockerhub/full-description.md
> Update description in Dockerhub

- standalone/script/runserver.sh
Add environment variable to configure default users password credentials.
> Configure default credentials standalone

- decisioncenter/Dockerfile
https://jsw.ibm.com/browse/DBACLD-47593
> Try to change java.security to fix memory leak

- decisionserver/decisionserverconsole/config/application.xml
- decisionserver/decisionserverruntime/config/application.xml
Under decision service application, add a common library for ml integration
> For DBACLD-131396

- decisionserver/decisionserverconsole/config/application.xml
- decisionserver/decisionserverruntime/config/application.xml
Reverts DecisionsDev/odm-ondocker#352
> Revert "For DBACLD-131396"
